=== HTTP-RPC/Sierra/sierra.dtd
<!ENTITY % org.httprpc.sierra.UILoader "name CDATA group CDATA label CDATA title CDATA titleColor CDATA titleFont CDATA titleJustification (left|right|center|leading|trailing) titlePosition (above-top|top|below-top|above-bottom|bottom|below-bottom) border CDATA padding CDATA weight CDATA size CDATA tabTitle CDATA tabIcon CDATA style CDATA styleClass CDATA ">
<!ENTITY % java.awt.Component "%org.httprpc.sierra.UILoader; background CDATA enabled (true|false) focusTraversalKeysEnabled (true|false) focusable (true|false) font CDATA foreground CDATA ignoreRepaint (true|false) name CDATA visible (true|false) ">
<!ENTITY % java.awt.Container "%java.awt.Component; focusCycleRoot (true|false) focusTraversalPolicyProvider (true|false) font CDATA ">
<!ENTITY % javax.swing.JComponent "%java.awt.Container; alignmentX CDATA alignmentY CDATA autoscrolls (true|false) background CDATA debugGraphicsOptions CDATA doubleBuffered (true|false) enabled (true|false) font CDATA foreground CDATA inheritsPopupMenu (true|false) opaque (true|false) requestFocusEnabled (true|false) toolTipText CDATA verifyInputWhenFocusTarget (true|false) visible (true|false) ">
<!ENTITY % javax.swing.AbstractButton "%javax.swing.JComponent; actionCommand CDATA borderPainted (true|false) contentAreaFilled (true|false) disabledIcon CDATA disabledSelectedIcon CDATA displayedMnemonicIndex CDATA enabled (true|false) focusPainted (true|false) hideActionText (true|false) horizontalAlignment (left|right|center|leading|trailing) horizontalTextPosition (left|right|center|leading|trailing) icon CDATA iconTextGap CDATA label CDATA mnemonic CDATA multiClickThreshhold CDATA pressedIcon CDATA rolloverEnabled (true|false) rolloverIcon CDATA rolloverSelectedIcon CDATA selected (true|false) selectedIcon CDATA text CDATA verticalAlignment (top|bottom|center) verticalTextPosition (top|bottom|center) ">
<!ENTITY % javax.swing.JColorChooser "%javax.swing.JComponent; color CDATA dragEnabled (true|false) ">
<!ELEMENT color-chooser EMPTY>
<!ATTLIST color-chooser %javax.swing.JColorChooser;>
<!ENTITY % javax.swing.JComboBox "%javax.swing.JComponent; actionCommand CDATA editable (true|false) enabled (true|false) lightWeightPopupEnabled (true|false) maximumRowCount CDATA popupVisible (true|false) selectedIndex CDATA ">
<!ELEMENT combo-box EMPTY>
<!ATTLIST combo-box %javax.swing.JComboBox;>
<!ENTITY % javax.swing.JLabel "%javax.swing.JComponent; disabledIcon CDATA displayedMnemonic CDATA displayedMnemonicIndex CDATA horizontalAlignment (left|right|center|leading|trailing) horizontalTextPosition (left|right|center|leading|trailing) icon CDATA iconTextGap CDATA text CDATA verticalAlignment (top|bottom|center) verticalTextPosition (top|bottom|center) ">
<!ELEMENT label EMPTY>
<!ATTLIST label %javax.swing.JLabel;>
<!ENTITY % javax.swing.JList "%javax.swing.JComponent; dragEnabled (true|false) dropMode (use-selection|on|insert|insert-rows|insert-cols|on-or-insert|on-or-insert-rows|on-or-insert-cols) fixedCellHeight CDATA fixedCellWidth CDATA layoutOrientation (vertical|vertical-wrap|horizontal-wrap) selectedIndex CDATA selectionBackground CDATA selectionForeground CDATA selectionMode (single-selection|single-interval-selection|multiple-interval-selection) valueIsAdjusting (true|false) visibleRowCount CDATA ">
<!ELEMENT list EMPTY>
<!ATTLIST list %javax.swing.JList;>
<!ENTITY % javax.swing.JMenuBar "%javax.swing.JComponent; borderPainted (true|false) ">
<!ELEMENT menu-bar (ANY)>
<!ATTLIST menu-bar %javax.swing.JMenuBar;>
<!ENTITY % javax.swing.JPanel "%javax.swing.JComponent; ">
<!ENTITY % javax.swing.JProgressBar "%javax.swing.JComponent; borderPainted (true|false) indeterminate (true|false) maximum CDATA minimum CDATA orientation (horizontal|vertical) string CDATA stringPainted (true|false) value CDATA ">
<!ELEMENT progress-bar EMPTY>
<!ATTLIST progress-bar %javax.swing.JProgressBar;>
<!ENTITY % javax.swing.JScrollPane "%javax.swing.JComponent; horizontalScrollBarPolicy (as-needed|never|always) verticalScrollBarPolicy (as-needed|never|always) wheelScrollingEnabled (true|false) ">
<!ELEMENT scroll-pane (ANY)>
<!ATTLIST scroll-pane %javax.swing.JScrollPane;>
<!ENTITY % javax.swing.JSeparator "%javax.swing.JComponent; orientation (horizontal|vertical) ">
<!ELEMENT separator EMPTY>
<!ATTLIST separator %javax.swing.JSeparator;>
<!ENTITY % javax.swing.JSlider "%javax.swing.JComponent; extent CDATA font CDATA inverted (true|false) majorTickSpacing CDATA maximum CDATA minimum CDATA minorTickSpacing CDATA orientation (horizontal|vertical) paintLabels (true|false) paintTicks (true|false) paintTrack (true|false) snapToTicks (true|false) value CDATA valueIsAdjusting (true|false) ">
<!ELEMENT slider EMPTY>
<!ATTLIST slider %javax.swing.JSlider;>
<!ENTITY % javax.swing.JSpinner "%javax.swing.JComponent; ">
<!ELEMENT spinner EMPTY>
<!ATTLIST spinner %javax.swing.JSpinner;>
<!ENTITY % javax.swing.JSplitPane "%javax.swing.JComponent; continuousLayout (true|false) dividerLocation CDATA dividerSize CDATA lastDividerLocation CDATA oneTouchExpandable (true|false) orientation (horizontal|vertical) resizeWeight CDATA ">
<!ELEMENT split-pane (ANY)>
<!ATTLIST split-pane %javax.swing.JSplitPane;>
<!ENTITY % javax.swing.JTabbedPane "%javax.swing.JComponent; selectedIndex CDATA tabLayoutPolicy (wrap-tab-layout|scroll-tab-layout) tabPlacement (top|left|bottom|right) ">
<!ELEMENT tabbed-pane (ANY)>
<!ATTLIST tabbed-pane %javax.swing.JTabbedPane;>
<!ENTITY % javax.swing.JTable "%javax.swing.JComponent; autoCreateColumnsFromModel (true|false) autoCreateRowSorter (true|false) autoResizeMode (off|next-column|subsequent-columns|last-column|all-columns) cellSelectionEnabled (true|false) columnSelectionAllowed (true|false) dragEnabled (true|false) dropMode (use-selection|on|insert|insert-rows|insert-cols|on-or-insert|on-or-insert-rows|on-or-insert-cols) editingColumn CDATA editingRow CDATA fillsViewportHeight (true|false) gridColor CDATA rowHeight CDATA rowMargin CDATA rowSelectionAllowed (true|false) selectionBackground CDATA selectionForeground CDATA showHorizontalLines (true|false) showVerticalLines (true|false) surrendersFocusOnKeystroke (true|false) updateSelectionOnSort (true|false) ">
<!ENTITY % javax.swing.JToolBar "%javax.swing.JComponent; borderPainted (true|false) floatable (true|false) orientation (horizontal|vertical) rollover (true|false) ">
<!ELEMENT tool-bar (ANY)>
<!ATTLIST tool-bar %javax.swing.JToolBar;>
<!ENTITY % javax.swing.JTree "%javax.swing.JComponent; dragEnabled (true|false) dropMode (use-selection|on|insert|insert-rows|insert-cols|on-or-insert|on-or-insert-rows|on-or-insert-cols) editable (true|false) expandsSelectedPaths (true|false) invokesStopCellEditing (true|false) largeModel (true|false) rootVisible (true|false) rowHeight CDATA scrollsOnExpand (true|false) showsRootHandles (true|false) toggleClickCount CDATA visibleRowCount CDATA ">
<!ENTITY % javax.swing.text.JTextComponent "%javax.swing.JComponent; caretColor CDATA caretPosition CDATA disabledTextColor CDATA dragEnabled (true|false) dropMode (use-selection|on|insert|insert-rows|insert-cols|on-or-insert|on-or-insert-rows|on-or-insert-cols) editable (true|false) focusAccelerator CDATA selectedTextColor CDATA selectionColor CDATA selectionEnd CDATA selectionStart CDATA text CDATA ">
<!ENTITY % org.httprpc.sierra.ActivityIndicator "%javax.swing.JComponent; indicatorSize CDATA ">
<!ELEMENT activity-indicator EMPTY>
<!ATTLIST activity-indicator %org.httprpc.sierra.ActivityIndicator;>
<!ENTITY % org.httprpc.sierra.Badge "%javax.swing.JComponent; outline CDATA text CDATA ">
<!ELEMENT badge EMPTY>
<!ATTLIST badge %org.httprpc.sierra.Badge;>
<!ENTITY % org.httprpc.sierra.ChartPane "%javax.swing.JComponent; ">
<!ELEMENT chart-pane EMPTY>
<!ATTLIST chart-pane %org.httprpc.sierra.ChartPane;>
<!ENTITY % org.httprpc.sierra.ImagePane "%javax.swing.JComponent; horizontalAlignment (left|right|center|leading|trailing) image CDATA interpolationMode (nearest-neighbor|bilinear|bicubic) scaleMode (none|fill-width|fill-height) verticalAlignment (top|bottom|center) ">
<!ELEMENT image-pane EMPTY>
<!ATTLIST image-pane %org.httprpc.sierra.ImagePane;>
<!ENTITY % org.httprpc.sierra.Spacer "%javax.swing.JComponent; ">
<!ELEMENT spacer EMPTY>
<!ATTLIST spacer %org.httprpc.sierra.Spacer;>
<!ENTITY % org.httprpc.sierra.TextPane "%javax.swing.JComponent; horizontalAlignment (left|right|center|leading|trailing) text CDATA verticalAlignment (top|bottom|center) wrapText (true|false) ">
<!ELEMENT text-pane EMPTY>
<!ATTLIST text-pane %org.httprpc.sierra.TextPane;>
<!ENTITY % javax.swing.JButton "%javax.swing.AbstractButton; defaultCapable (true|false) ">
<!ELEMENT button EMPTY>
<!ATTLIST button %javax.swing.JButton;>
<!ENTITY % javax.swing.JMenuItem "%javax.swing.AbstractButton; accelerator CDATA armed (true|false) enabled (true|false) ">
<!ELEMENT menu-item EMPTY>
<!ATTLIST menu-item %javax.swing.JMenuItem;>
<!ENTITY % javax.swing.JPopupMenu.Separator "%javax.swing.JSeparator; ">
<!ELEMENT popup-menu-separator EMPTY>
<!ATTLIST popup-menu-separator %javax.swing.JPopupMenu.Separator;>
<!ENTITY % javax.swing.JTextArea "%javax.swing.text.JTextComponent; columns CDATA font CDATA lineWrap (true|false) rows CDATA tabSize CDATA wrapStyleWord (true|false) ">
<!ELEMENT text-area EMPTY>
<!ATTLIST text-area %javax.swing.JTextArea;>
<!ENTITY % javax.swing.JTextField "%javax.swing.text.JTextComponent; columns CDATA font CDATA horizontalAlignment (left|right|center|leading|trailing) scrollOffset CDATA placeholderText CDATA showClearButton (true|false) leadingIcon CDATA trailingIcon CDATA ">
<!ELEMENT text-field EMPTY>
<!ATTLIST text-field %javax.swing.JTextField;>
<!ENTITY % javax.swing.JToggleButton "%javax.swing.AbstractButton; ">
<!ELEMENT toggle-button EMPTY>
<!ATTLIST toggle-button %javax.swing.JToggleButton;>
<!ENTITY % javax.swing.JToolBar.Separator "%javax.swing.JSeparator; ">
<!ELEMENT tool-bar-separator EMPTY>
<!ATTLIST tool-bar-separator %javax.swing.JToolBar.Separator;>
<!ENTITY % org.httprpc.sierra.FormPanel "%javax.swing.JPanel; horizontalSpacing CDATA verticalSpacing CDATA ">
<!ELEMENT form-panel (ANY)>
<!ATTLIST form-panel %org.httprpc.sierra.FormPanel;>
<!ENTITY % org.httprpc.sierra.LayoutPanel "%javax.swing.JPanel; scrollableTracksViewportHeight (true|false) scrollableTracksViewportWidth (true|false) ">
<!ENTITY % org.httprpc.sierra.UILoader.JxTable "%javax.swing.JTable; columnSelectionMode (single-selection|single-interval-selection|multiple-interval-selection) rowSelectionMode (single-selection|single-interval-selection|multiple-interval-selection) ">
<!ELEMENT table EMPTY>
<!ATTLIST table %org.httprpc.sierra.UILoader.JxTable;>
<!ENTITY % org.httprpc.sierra.UILoader.JxTree "%javax.swing.JTree; selectionMode (single-tree-selection|contiguous-tree-selection|discontiguous-tree-selection) ">
<!ELEMENT tree EMPTY>
<!ATTLIST tree %org.httprpc.sierra.UILoader.JxTree;>
<!ENTITY % javax.swing.JCheckBox "%javax.swing.JToggleButton; borderPaintedFlat (true|false) ">
<!ELEMENT check-box EMPTY>
<!ATTLIST check-box %javax.swing.JCheckBox;>
<!ENTITY % javax.swing.JCheckBoxMenuItem "%javax.swing.JMenuItem; state (true|false) ">
<!ELEMENT check-box-menu-item EMPTY>
<!ATTLIST check-box-menu-item %javax.swing.JCheckBoxMenuItem;>
<!ENTITY % javax.swing.JFormattedTextField "%javax.swing.JTextField; focusLostBehavior (commit|commit-or-revert|revert|persist) ">
<!ELEMENT formatted-text-field EMPTY>
<!ATTLIST formatted-text-field %javax.swing.JFormattedTextField;>
<!ENTITY % javax.swing.JMenu "%javax.swing.JMenuItem; accelerator CDATA delay CDATA popupMenuVisible (true|false) selected (true|false) ">
<!ELEMENT menu (ANY)>
<!ATTLIST menu %javax.swing.JMenu;>
<!ENTITY % javax.swing.JPasswordField "%javax.swing.JTextField; echoChar CDATA text CDATA ">
<!ELEMENT password-field EMPTY>
<!ATTLIST password-field %javax.swing.JPasswordField;>
<!ENTITY % javax.swing.JRadioButton "%javax.swing.JToggleButton; ">
<!ELEMENT radio-button EMPTY>
<!ATTLIST radio-button %javax.swing.JRadioButton;>
<!ENTITY % javax.swing.JRadioButtonMenuItem "%javax.swing.JMenuItem; ">
<!ELEMENT radio-button-menu-item EMPTY>
<!ATTLIST radio-button-menu-item %javax.swing.JRadioButtonMenuItem;>
<!ENTITY % org.httprpc.sierra.BoxPanel "%org.httprpc.sierra.LayoutPanel; spacing CDATA ">
<!ENTITY % org.httprpc.sierra.MenuButton "%javax.swing.JButton; popupHorizontalAlignment (left|right|center|leading|trailing) popupVerticalAlignment (top|bottom|center) ">
<!ELEMENT menu-button (ANY)>
<!ATTLIST menu-button %org.httprpc.sierra.MenuButton;>
<!ENTITY % org.httprpc.sierra.NumberField "%javax.swing.JTextField; value CDATA ">
<!ELEMENT number-field EMPTY>
<!ATTLIST number-field %org.httprpc.sierra.NumberField;>
<!ENTITY % org.httprpc.sierra.Picker "%javax.swing.JTextField; popupHorizontalAlignment (left|right|center|leading|trailing) popupVerticalAlignment (top|bottom|center) ">
<!ENTITY % org.httprpc.sierra.StackPanel "%org.httprpc.sierra.LayoutPanel; ">
<!ELEMENT stack-panel (ANY)>
<!ATTLIST stack-panel %org.httprpc.sierra.StackPanel;>
<!ENTITY % org.httprpc.sierra.ValidatedTextField "%javax.swing.JTextField; pattern CDATA value CDATA ">
<!ELEMENT validated-text-field EMPTY>
<!ATTLIST validated-text-field %org.httprpc.sierra.ValidatedTextField;>
<!ENTITY % org.httprpc.sierra.ColumnPanel "%org.httprpc.sierra.BoxPanel; alignToGrid (true|false) ">
<!ELEMENT column-panel (ANY)>
<!ATTLIST column-panel %org.httprpc.sierra.ColumnPanel;>
<!ENTITY % org.httprpc.sierra.RowPanel "%org.httprpc.sierra.BoxPanel; alignToBaseline (true|false) ">
<!ELEMENT row-panel (ANY)>
<!ATTLIST row-panel %org.httprpc.sierra.RowPanel;>
<!ENTITY % org.httprpc.sierra.SuggestionPicker "%org.httprpc.sierra.Picker; maximumRowCount CDATA ">
<!ELEMENT suggestion-picker EMPTY>
<!ATTLIST suggestion-picker %org.httprpc.sierra.SuggestionPicker;>
<!ENTITY % org.httprpc.sierra.TemporalPicker "%org.httprpc.sierra.Picker; ">
<!ENTITY % org.httprpc.sierra.DatePicker "%org.httprpc.sierra.TemporalPicker; ">
<!ELEMENT date-picker EMPTY>
<!ATTLIST date-picker %org.httprpc.sierra.DatePicker;>
<!ENTITY % org.httprpc.sierra.TimePicker "%org.httprpc.sierra.TemporalPicker; minuteInterval CDATA strict (true|false) ">
<!ELEMENT time-picker EMPTY>
<!ATTLIST time-picker %org.httprpc.sierra.TimePicker;>

=== HTTP-RPC/Sierra/sierra-test/src/main/resources/org/httprpc/sierra/test/MenuTest.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE column-panel SYSTEM "sierra.dtd">

<column-panel>
    <menu-bar>
        <menu text="Menu">
            <menu-item text="One"/>
            <menu-item text="Two"/>
            <menu-item text="Three"/>
            <popup-menu-separator/>
            <check-box-menu-item text="Selection A" selected="true"/>
            <check-box-menu-item text="Selection B"/>
            <popup-menu-separator/>
            <radio-button text="Option 1" group="options" selected="true"/>
            <radio-button text="Option 2" group="options"/>
            <radio-button text="Option 3" group="options"/>
        </menu>
    </menu-bar>

    <spacer/>
</column-panel>

=== HTTP-RPC/Sierra/sierra-test/src/main/resources/org/httprpc/sierra/test/TiingoTest.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE column-panel SYSTEM "sierra.dtd">

<column-panel spacing="8" padding="8" opaque="true">
    <row-panel spacing="8">
        <row-panel spacing="4">
            <label text="ticker"/>
            <text-field name="tickerTextField" columns="6"/>
        </row-panel>

        <row-panel spacing="4">
            <label text="count"/>
            <spinner name="countSpinner"/>
        </row-panel>

        <activity-indicator name="activityIndicator" indicatorSize="18"/>

        <spacer weight="1"/>

        <button name="submitButton" text="submit"/>
    </row-panel>

    <separator/>

    <row-panel spacing="8" weight="1">
        <column-panel spacing="4">
            <form-panel>
                <text-field name="nameTextField" label="name" columns="16" editable="false"/>
                <text-field name="exchangeCodeTextField" label="exchangeCode" columns="6" editable="false"/>
                <text-field name="startDateTextField" label="startDate" columns="12" editable="false"/>
                <text-field name="endDateTextField" label="endDate" columns="12" editable="false"/>
            </form-panel>

            <separator/>

            <scroll-pane weight="1">
                <text-area name="descriptionTextArea" editable="false" lineWrap="true" wrapStyleWord="true"/>
            </scroll-pane>
        </column-panel>

        <separator orientation="vertical"/>

        <tabbed-pane style="showContentSeparator: false" weight="1">
            <scroll-pane tabTitle="table">
                <table name="historicalPricingTable" rowSelectionMode="single-selection"/>
            </scroll-pane>

            <chart-pane name="historicalPricingChartPane" tabTitle="chart" padding="8"
                opaque="true" background="TextArea.background"
                border="Component.borderColor"/>
        </tabbed-pane>
    </row-panel>
</column-panel>

=== HTTP-RPC/Sierra/sierra-tools/previewer/src/main/resources/org/httprpc/sierra/tools/previewer/MainFrame.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE column-panel SYSTEM "sierra.dtd">

<column-panel>
    <menu-bar name="menuBar">
        <menu text="File">
            <menu-item name="openItem" text="Open..."/>
            <menu name="recentMenu" text="Recent"/>
            <popup-menu-separator/>
            <menu-item name="saveItem" text="Save"/>
            <popup-menu-separator/>
            <menu-item name="exitItem" text="Exit"/>
        </menu>
        <menu name="searchMenu" text="Search">
            <menu-item name="findItem" text="Find"/>
            <menu-item name="replaceItem" text="Replace"/>            
        </menu>        
        <menu text="About">
            <menu-item name="aboutItem" text="About Previewer"/>
        </menu>
    </menu-bar>

    <split-pane name="splitPane" resizeWeight="0.5" weight="1">
        <scroll-pane name="editorScrollPane" weight="1"/>
        <column-panel name="previewPanel" padding="5, 5, 5, 5" weight="1"/>
    </split-pane>

    <label name="filePathLabel" text="" padding="4, 6, 4, 6" />
    <label name="statusBar" text="Ready." padding="2, 5, 2, 5" border="silver, 1"/>
</column-panel>

=== HTTP-RPC/Sierra/sierra-test/src/main/resources/org/httprpc/sierra/test/suggestion-picker-test.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE column-panel SYSTEM "sierra.dtd">

<column-panel spacing="4" alignToGrid="true" padding="8">
    <row-panel alignToBaseline="true">
        <label text="Quantity" alignmentX="1.0"/>
        <text-field columns="6" alignmentX="0.0"/>
    </row-panel>
    <row-panel alignToBaseline="true">
        <label text="Size" alignmentX="1.0"/>
        <suggestion-picker name="sizeSuggestionPicker" columns="10" alignmentX="0.0"/>
    </row-panel>
    <row-panel alignToBaseline="true">
        <label text="Color" alignmentX="1.0"/>
        <suggestion-picker name="colorSuggestionPicker" columns="10" maximumRowCount="4" alignmentX="0.0"/>
    </row-panel>
    <spacer weight="1"/>
</column-panel>

=== HTTP-RPC/Sierra/sierra-test/src/main/resources/org/httprpc/sierra/test/TaskExecutorTest.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE column-panel SYSTEM "sierra.dtd">

<column-panel spacing="8" padding="8" opaque="true">
    <column-panel>
        <check-box text="Check box 1"/>
        <check-box text="Check box 2"/>
    </column-panel>

    <row-panel spacing="8">
        <button name="button" text="Execute Task"/>
        <label name="label" foreground="gray"/>
        <spacer weight="1"/>
        <activity-indicator name="activityIndicator" indicatorSize="18"/>
    </row-panel>
</column-panel>
