=== HTTP-RPC/Sierra/sierra-test/src/main/resources/org/httprpc/sierra/test/sierra.dtd
<!ENTITY % UILoader "name ID border CDATA padding CDATA weight CDATA size CDATA">

<!ENTITY % JComponent "%UILoader; background CDATA foreground CDATA opaque (true|false)">

<!ENTITY % ImagePane "%JComponent; image CDATA scaleMode (none|fill-width|fill-height) horizontalAlignment (leading|trailing|center) verticalAlignment (top|bottom|center)">
<!ELEMENT image-pane EMPTY>
<!ATTLIST image-pane %ImagePane;>

<!ENTITY % JButton "%JComponent; text CDATA ">
<!ELEMENT button EMPTY>
<!ATTLIST button %JButton;>

<!ENTITY % JLabel "%JComponent; text CDATA horizontalAlignment (left|center|right|leading|trailing) verticalAlignment (top|center|bottom)">
<!ELEMENT label EMPTY>
<!ATTLIST label %JLabel;>

<!ENTITY % JPanel "%JComponent; ">

<!ENTITY % Spacer "%JComponent; ">
<!ELEMENT spacer EMPTY>
<!ATTLIST spacer %Spacer;>

<!ENTITY % TextPane "%JComponent; text CDATA wrapText (true|false) horizontalAlignment (leading|trailing|center) verticalAlignment (top|bottom|center)">
<!ELEMENT text-pane EMPTY>
<!ATTLIST text-pane %TextPane;>

<!ENTITY % LayoutPanel "%JPanel; scrollableTracksViewportWidth (true|false) scrollableTracksViewportHeight (true|false)">

<!ENTITY % BoxPanel "%LayoutPanel; spacing CDATA">

<!ENTITY % ColumnPanel "%BoxPanel; alignToGrid (true|false)">
<!ELEMENT column-panel (ANY)>
<!ATTLIST column-panel %ColumnPanel;>

<!ENTITY % RowPanel "%BoxPanel; alignToBaseline (true|false)">
<!ELEMENT row-panel (ANY)>
<!ATTLIST row-panel %RowPanel;>

=== HTTP-RPC/Sierra/sierra-test/src/main/resources/org/httprpc/sierra/test/AlignmentYTest.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE column-panel SYSTEM "sierra.dtd">

<column-panel spacing="4" padding="8" alignToGrid="true" opaque="true">
    <row-panel>
        <text-pane text="0.0" alignmentY="0.0" border="silver"/>
        <spacer size="160, 80" border="silver"/>
    </row-panel>
    <row-panel>
        <text-pane text="0.25" verticalAlignment="center" alignmentY="0.25" border="silver"/>
        <spacer size="160, 80" border="silver"/>
    </row-panel>
    <row-panel>
        <text-pane text="0.5" verticalAlignment="center" alignmentY="0.5" border="silver"/>
        <spacer size="160, 80" border="silver"/>
    </row-panel>
    <row-panel>
        <text-pane text="0.75" verticalAlignment="center" alignmentY="0.75" border="silver"/>
        <spacer size="160, 80" border="silver"/>
    </row-panel>
    <row-panel>
        <text-pane text="1.0" alignmentY="1.0" border="silver"/>
        <spacer size="160, 80" border="silver"/>
    </row-panel>
</column-panel>

=== HTTP-RPC/Sierra/sierra-test/src/main/resources/org/httprpc/sierra/test/block-layout-test.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE column-panel SYSTEM "sierra.dtd">

<column-panel spacing="4" padding="8" scrollableTracksViewportWidth="true">
    <text-pane text="Heading 1" font="h1.font" wrapText="true"/>
    <text-pane text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua." wrapText="true"/>

    <spacer size="4"/>

    <text-pane text="Heading 2a" font="h2.font" wrapText="true"/>
    <text-pane text="Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat." wrapText="true"/>

    <row-panel>
        <spacer weight="1"/>
        <image-pane image="world.png" scaleMode="fill-width" size="120"/>
        <spacer weight="1"/>
    </row-panel>

    <spacer size="4"/>

    <text-pane text="Heading 2b" font="h2.font" wrapText="true"/>
    <text-pane text="Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur." wrapText="true"/>

    <column-panel padding="0, 8, 0, 0">
        <row-panel spacing="4">
            <text-pane text="•"/>
            <text-pane text="Excepteur sint occaecat cupidatat non proident" wrapText="true" weight="1"/>
        </row-panel>
        <row-panel spacing="4">
            <text-pane text="•"/>
            <text-pane text="Sunt in culpa qui officia deserunt" wrapText="true" weight="1"/>
        </row-panel>
        <row-panel spacing="4">
            <text-pane text="•"/>
            <text-pane text="Mollit anim id est laborum" wrapText="true" weight="1"/>
        </row-panel>
    </column-panel>
</column-panel>

=== HTTP-RPC/Sierra/sierra-test/src/main/resources/org/httprpc/sierra/test/number-field-test.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE column-panel SYSTEM "sierra.dtd">

<column-panel padding="8">
    <column-panel spacing="4" alignToGrid="true">
        <row-panel>
            <label text="default"/>
            <number-field name="defaultNumberField" columns="8"/>
        </row-panel>
        <row-panel>
            <label text="custom"/>
            <number-field name="customNumberField" columns="8"/>
        </row-panel>
    </column-panel>

    <spacer weight="1"/>

    <label name="selectionLabel" horizontalAlignment="center"/>
</column-panel>

=== HTTP-RPC/Sierra/sierra-test/src/main/resources/org/httprpc/sierra/test/AlignmentXTest.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE column-panel SYSTEM "sierra.dtd">

<column-panel spacing="4" padding="8" alignToGrid="true">
    <row-panel>
        <text-pane text="0.0" alignmentX="0.0" border="silver"/>
        <text-pane text="0.25" horizontalAlignment="center" alignmentX="0.25" border="silver"/>
        <text-pane text="0.5" horizontalAlignment="center" alignmentX="0.5" border="silver"/>
        <text-pane text="0.75" horizontalAlignment="center" alignmentX="0.75" border="silver"/>
        <text-pane text="1.0" alignmentX="1.0" border="silver"/>
    </row-panel>

    <row-panel>
        <spacer size="120, 40" border="silver"/>
        <spacer size="120, 40" border="silver"/>
        <spacer size="120, 40" border="silver"/>
        <spacer size="120, 40" border="silver"/>
        <spacer size="120, 40" border="silver"/>
    </row-panel>
</column-panel>

=== HTTP-RPC/Sierra/sierra-test/src/main/resources/org/httprpc/sierra/test/validated-input-test.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE column-panel SYSTEM "sierra.dtd">

<column-panel padding="8">
    <column-panel spacing="4" alignToGrid="true">
        <row-panel>
            <label text="number1"/>
            <number-field name="numberField1" columns="8"/>
        </row-panel>
        <row-panel>
            <label text="number2"/>
            <number-field name="numberField2" columns="8"/>
        </row-panel>
        <row-panel>
            <label text="validatedText"/>
            <validated-text-field name="validatedTextField" columns="8" pattern="validatedTextPattern"/>
        </row-panel>
        <row-panel>
            <spacer/>
            <button name="submitButton" text="submit"/>
        </row-panel>
    </column-panel>

    <spacer weight="1"/>

    <label name="messageLabel" horizontalAlignment="center"/>
</column-panel>

=== HTTP-RPC/Sierra/sierra-test/src/main/resources/org/httprpc/sierra/test/alignment-test.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE column-panel SYSTEM "sierra.dtd">

<column-panel spacing="4" alignToGrid="true" padding="8">
    <row-panel>
        <text-pane text="A" horizontalAlignment="center" alignmentX="0.25" alignmentY="0.0" border="silver"/>
        <spacer size="60, 45" border="silver"/>
        <text-pane text="B" verticalAlignment="center" alignmentX="0.0" alignmentY="0.75" border="silver"/>
    </row-panel>

    <row-panel>
        <spacer size="120, 45" border="silver"/>
        <text-pane text="C" horizontalAlignment="center" verticalAlignment="center" border="silver"/>
        <spacer size="120, 45" border="silver"/>
    </row-panel>

    <row-panel>
        <text-pane text="D" verticalAlignment="center" alignmentX="1.0" alignmentY="0.25" border="silver"/>
        <spacer size="0, 45" border="silver"/>
        <text-pane text="E" horizontalAlignment="center" alignmentX="0.75" alignmentY="1.0" border="silver"/>
    </row-panel>
</column-panel>
